common: &common
  alps_base_uri: http://localhost:3000/alps
  deployment_base_uri: http://localhost:3000
  discovery_base_uri: http://localhost:3000
  documentation_base_uri: http://docs.restfest2014.apiary.io/reference
  crichton_proxy_base_uri: http://localhost:3000/crichton
  use_alps_middleware: true
  alps_profile_response_expiry: 20
  use_discovery_middleware: true
  resource_home_response_expiry: 20
  service_level_target_header: REQUEST_SLT
  css_uri: 
  js_uri: 
production: *common
development: *common
test: *common
